Repository nebari-dev/nebari-docker-images, pull requests merged in 2022-07, with the labels that each got.

#4 🔄 Synced file(s) with nebari-dev/.github
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/general-issue.yml
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  LICENSE
Labels: type: file sync ♻️

#1 Transfer images
  .github/workflows/build-push-docker.yaml
  .hadolint.yaml
  Dockerfile.dask-worker
  Dockerfile.jupyterhub
  Dockerfile.jupyterlab
  README.md
  dask-worker/environment.yaml
  dask-worker/postBuild
  docker-bake.json
  jupyterhub/environment.yaml
  jupyterhub/postBuild
  jupyterlab/apt.txt
  jupyterlab/conda-linux-64.lock
  jupyterlab/environment.yaml
  jupyterlab/postBuild
  scripts/fix-permissions
  scripts/install-apt-minimal.sh
  scripts/install-apt.sh
  scripts/install-conda-environment.sh
  scripts/install-conda.sh
Labels: area: ci 👷🏽‍♀️, area: dependencies 📦, needs: changes

#6 [ENH] - Applying some improvements to docs
  .dockerignore
  .github/workflows/build-push-docker.yaml
  .gitignore
  .hadolint.yaml
  .pre-commit-config.yaml
  README.md
  dask-worker/environment.yaml
  docker-bake.json
  jupyterhub/environment.yaml
  jupyterlab/environment.yaml
Labels: needs: review 👀, area: documentation 📖, type: enhancement 💅🏼

#7 Fix Docker build action
  .github/workflows/build-push-docker.yaml
Labels: area: ci 👷🏽‍♀️, needs: review 👀, type: maintenance 🛠
