Repository nebari-dev/nebari-docker-images, pull requests merged in 2023-11, with the labels that each got.

#93 Use bokeh>=3.0
  jupyterlab/environment.yaml
Labels: area: dependencies 📦

#98 Add jupyter_ai
  jupyterlab/environment.yaml
Labels: area: dependencies 📦, type: enhancement 💅🏼

#96 Upgrade images to CUDA 12
  .github/workflows/build-push-docker.yaml
  .github/workflows/test-images.yaml
Labels: area: dependencies 📦

#97 Pin ipywidgets greater than version 8
  jupyterlab/environment.yaml
Labels: area: dependencies 📦

#99 Update jupyterlab-conda-store to latest version
  jupyterlab/environment.yaml
Labels: type: maintenance 🛠
